# Generated by Django 6.0.1 on 2026-01-07 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='hotel_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking_app.hotel'),
        ),
        migrations.AddField(
            model_name='booking',
            name='hotel_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking_app.hotel'),
        ),
        migrations.AddField(
            model_name='booking',
            name='room_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking_app.room'),
        ),
        migrations.AddField(
            model_name='booking',
            name='room_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking_app.room'),
        ),
        migrations.AddField(
            model_name='city',
            name='city_name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='city_name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='country_name_en',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='country_name_ru',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='city_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking_app.city'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='city_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking_app.city'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='country_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking_app.country'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='country_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking_app.country'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_service_en',
            field=models.ManyToManyField(null=True, to='booking_app.service'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_service_ru',
            field=models.ManyToManyField(null=True, to='booking_app.service'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='street_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='street_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='comment_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='comment_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='hotel_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking_app.hotel'),
        ),
        migrations.AddField(
            model_name='review',
            name='hotel_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking_app.hotel'),
        ),
        migrations.AddField(
            model_name='room',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='hotel_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking_app.hotel'),
        ),
        migrations.AddField(
            model_name='room',
            name='hotel_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking_app.hotel'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_status_en',
            field=models.CharField(choices=[('Занят', 'Занят'), ('Свободен', 'Свободен'), ('Забронорован', 'Забронорован')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_status_ru',
            field=models.CharField(choices=[('Занят', 'Занят'), ('Свободен', 'Свободен'), ('Забронорован', 'Забронорован')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type_en',
            field=models.CharField(choices=[('Люкс', 'Люкс'), ('Полулюкс', 'Полулюкс'), ('Семеный', 'Семеный'), ('Эконом', 'Эконом'), ('Одноместный', 'Одноместный')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type_ru',
            field=models.CharField(choices=[('Люкс', 'Люкс'), ('Полулюкс', 'Полулюкс'), ('Семеный', 'Семеный'), ('Эконом', 'Эконом'), ('Одноместный', 'Одноместный')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service_name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service_name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking_app.country'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking_app.country'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_role_en',
            field=models.CharField(choices=[('client', 'client'), ('owner', 'owner')], default='client', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_role_ru',
            field=models.CharField(choices=[('client', 'client'), ('owner', 'owner')], default='client', max_length=20, null=True),
        ),
    ]
