# Generated by Django 6.0.1 on 2026-01-07 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0002_booking_hotel_en_booking_hotel_ru_booking_room_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking_app.country'),
        ),
        migrations.AddField(
            model_name='city',
            name='country_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking_app.country'),
        ),
        migrations.AddField(
            model_name='city',
            name='country_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking_app.country'),
        ),
    ]
