# Generated by Django 6.0.1 on 2026-01-07 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0003_city_country_city_country_en_city_country_ru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='country_en',
        ),
        migrations.RemoveField(
            model_name='city',
            name='country_ru',
        ),
    ]
