# Generated by Django 6.0.1 on 2026-01-07 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0004_remove_city_country_en_remove_city_country_ru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='hotel_en',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='hotel_ru',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='room_en',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='room_ru',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='city_en',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='city_ru',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='country_en',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='country_ru',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_service_en',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_service_ru',
        ),
        migrations.RemoveField(
            model_name='review',
            name='hotel_en',
        ),
        migrations.RemoveField(
            model_name='review',
            name='hotel_ru',
        ),
        migrations.RemoveField(
            model_name='room',
            name='hotel_en',
        ),
        migrations.RemoveField(
            model_name='room',
            name='hotel_ru',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='country_en',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='country_ru',
        ),
    ]
