# Generated by Django 6.0 on 2026-01-10 16:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0005_remove_booking_hotel_en_remove_booking_hotel_ru_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='registered_date',
            new_name='register_date',
        ),
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_role_en',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_role_ru',
        ),
        migrations.AddField(
            model_name='city',
            name='city_name_ky',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='country_name_ky',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_name_ky',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='street_ky',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='comment_ky',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='description_ky',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_status_ky',
            field=models.CharField(choices=[('Занят', 'Занят'), ('Забронирован', 'Забронирован '), ('Свободен', 'Свободен ')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type_ky',
            field=models.CharField(choices=[('Люкс', 'Люкс'), ('Полулюкс', 'Полулюкс'), ('Семейный', 'Семейный'), ('Эконом', 'Эконом'), ('Одноместный', 'Одноместный')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service_name_ky',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_image',
            field=models.ImageField(upload_to='city_images'),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_image',
            field=models.ImageField(upload_to='country_image'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='booking_app.city'),
        ),
        migrations.AlterField(
            model_name='hotelimage',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_image', to='booking_app.hotel'),
        ),
        migrations.AlterField(
            model_name='hotelimage',
            name='hotel_image',
            field=models.ImageField(upload_to='hotel_images/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_reviews', to='booking_app.hotel'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')]),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_rooms', to='booking_app.hotel'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_status',
            field=models.CharField(choices=[('Занят', 'Занят'), ('Забронирован', 'Забронирован '), ('Свободен', 'Свободен ')], max_length=30),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_status_en',
            field=models.CharField(choices=[('Занят', 'Занят'), ('Забронирован', 'Забронирован '), ('Свободен', 'Свободен ')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_status_ru',
            field=models.CharField(choices=[('Занят', 'Занят'), ('Забронирован', 'Забронирован '), ('Свободен', 'Свободен ')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Люкс', 'Люкс'), ('Полулюкс', 'Полулюкс'), ('Семейный', 'Семейный'), ('Эконом', 'Эконом'), ('Одноместный', 'Одноместный')], max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type_en',
            field=models.CharField(choices=[('Люкс', 'Люкс'), ('Полулюкс', 'Полулюкс'), ('Семейный', 'Семейный'), ('Эконом', 'Эконом'), ('Одноместный', 'Одноместный')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type_ru',
            field=models.CharField(choices=[('Люкс', 'Люкс'), ('Полулюкс', 'Полулюкс'), ('Семейный', 'Семейный'), ('Эконом', 'Эконом'), ('Одноместный', 'Одноместный')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_photos', to='booking_app.room'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_image',
            field=models.ImageField(upload_to='service_images'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(80), django.core.validators.MinValueValidator(18)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_foto'),
        ),
    ]
