# Generated by Django 6.0 on 2026-01-11 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0006_rename_registered_date_userprofile_register_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='city_name_ky',
        ),
        migrations.RemoveField(
            model_name='country',
            name='country_name_ky',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='description_ky',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_name_ky',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='street_ky',
        ),
        migrations.RemoveField(
            model_name='review',
            name='comment_ky',
        ),
        migrations.RemoveField(
            model_name='room',
            name='description_ky',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_status_ky',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_type_ky',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_name_ky',
        ),
    ]
