# Generated by Django 6.0 on 2026-01-11 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0007_remove_city_city_name_ky_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
